<a href="https://colab.research.google.com/github/wagnermor/algebraLinear-Ada/blob/main/aula03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([
              [1,5,3],
              [3,2,1],
              [1,1,1]
])

y = np.array([
              [1],
              [0],
              [1]
])

print(a)
print()
print(y)

[[1 5 3]
 [3 2 1]
 [1 1 1]]

[[1]
 [0]
 [1]]


In [3]:
# Achando a matriz inversa de a

a_inv = np.linalg.inv(a)

print(a_inv)

[[-0.16666667  0.33333333  0.16666667]
 [ 0.33333333  0.33333333 -1.33333333]
 [-0.16666667 -0.66666667  2.16666667]]


In [4]:
# Calculando o resultado

x = np.dot(a_inv, y)

print(x)

[[ 0.]
 [-1.]
 [ 2.]]


In [5]:
# Resolvendo de forma alternativa

x = np.linalg.solve(a, y)

print(x)

[[ 0.]
 [-1.]
 [ 2.]]


In [6]:
# Determinantes

m = np.array([
              [1,0,1],
              [2,2,2],
              [-1,4,-2]
])
print(m)

[[ 1  0  1]
 [ 2  2  2]
 [-1  4 -2]]


In [7]:
det = np.linalg.det(m)

print(det)

-1.9999999999999993


In [12]:
import math as m
print(m.ceil(det))
print()
print(round(det))

-1

-2
