<a href="https://colab.research.google.com/github/wagnermor/algebraLinear-Ada/blob/main/aula02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([[0,1],[3,0]])

In [ ]:
print(a)

[[0 1]
 [3 0]]


In [ ]:
# Matriz Transpostas: Matriz que as linhas viram colunas, e as colunas viram linhas
# Operador T
t = a.transpose()

r = a.T

print(t)
print()
print(r)

[[0 3]
 [1 0]]

[[0 3]
 [1 0]]


In [ ]:
# Matriz identidade ---> Só faz sentido para Matrizes Quadradas (o n de linhas = n de colunas)
# A diagonal principal é 1 para todos os elementos, e o restante é igual a zero

[
  [1,0,0],
  [0,1,0],
  [0,0,1]
]

In [ ]:
id = np.eye(13)
print(id)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
# Matriz inversa

$$A . A^{-1} = I$$

In [ ]:
b = np.array([[0,1],[3,0]])
#i = np.eye(2)

# Calculando a invesa
b_inv = np.linalg.inv(b)

print(b)
print()
print(b_inv)

[[0 1]
 [3 0]]

[[0.         0.33333333]
 [1.         0.        ]]
